name: lshw # you probably want to 'snapcraft register <name>'
version: 'B.02.17' # just for humans, typically '1.2+git' or '1.3.2'
summary: snap to run lshw # 79 char long summary
description: |
  snap to run lshw version B.02.17.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
    lshw:
        command: usr/bin/lshw
        plugs: [hardware-observe]

parts:
    lshw:
        plugin: dump
        source: .
        stage-packages:
           - lshw
        build-packages:
           - lshw

